CREATE TABLE [dbo].[T_STUDENT]
(
	[StudentID] INT NOT NULL PRIMARY KEY IDENTITY,
	[BrojIndeksa] NVARCHAR (20) NOT NULL,
	[Ime] NVARCHAR (50) NOT NULL,
	[Prezime] NVARCHAR (50) NOT NULL,
	[Smer] NVARCHAR (50) NOT NULL,
	[Prosek] REAL NOT NULL
)
